## SP 500

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
#choose ticker from yahoo finance website
sp_500 = yf.Ticker('^GSPC')

#get the table inclusing the oldest data until current time
sp_df = sp_500.history(start = ('1928-01-01'), end = ('2023-04-01'))
#sp_df = sp_500.history(period = 'max')

#eliminate columns with no use
sp_df = sp_df.drop(['Dividends', 'Stock Splits'], axis = 1)

#transform the index 'Date' in a column
sp_df = sp_df.reset_index()

#eliminate the time from the 'Date' column
sp_df['Date'] = pd.to_datetime(sp_df['Date'])
sp_df['Date'] = sp_df['Date'].dt.date

#create a new column with % change from last close to new open
sp_df['% Change'] = np.nan
mask = (sp_df['Close'].shift() != np.nan) & (sp_df['Open'].notna())
sp_df.loc[mask, '% Change'] = ((sp_df['Open'] - sp_df['Close'].shift()) / sp_df['Close'].shift()) * 100

#realocate the % change column to the sixth spot
sp_df.insert(5, '% Change', sp_df.pop('% Change'))

#crate a new column with the % volume change
column_values = sp_df['Volume']
pct_diff = column_values.pct_change() * 100
sp_df['% Volume Change'] = pct_diff

#convert NaN in % columns to 0
sp_df['% Volume Change'] = sp_df['% Volume Change'].fillna(0)
sp_df['% Change'] = sp_df['% Change'].fillna(0)

#check if there is inf values in any column
for title in sp_df.columns: #['Date', 'Open', 'High', 'Low', 'Close', '% Change', 'Volume', '% Volume Change']:
    if sp_df[title].isin([np.inf, -np.inf]).any():
        print(f'The DataFrame contains infinite values in {title}.')
    else:
        print(f'The DataFrame does not contain infinite values in {title}.')
        
#locate how many inf elements there are in column % Volume Change
num_inf = np.isinf(sp_df['% Volume Change']).sum()
print(f'There are {num_inf} inf values')

# check the number of the rows contain inf values
inf_cols = sp_df.isin([np.inf, -np.inf]).any()
inf_rows = sp_df.isin([np.inf, -np.inf]).any(axis=1)
# print the columns and rows containing inf values
print("Rows containing inf: ", list(inf_rows[inf_rows == True].index))

#locate the row
inf_df = sp_df.isin([np.inf, -np.inf])
# get the rows containing inf values
inf_rows = sp_df.loc[inf_df.any(axis=1)]
print(inf_rows)

In [3]:
sp_df.tail(100)

,Date,Open,High,Low,Close,% Change,Volume,% Volume Change
23826,2022-11-07,3780.709961,3813.949951,3764.699951,3806.800049,0.269454,4341620000,-19.602310
23827,2022-11-08,3817.020020,3859.399902,3786.280029,3828.110107,0.268466,4607640000,6.127206
23828,2022-11-09,3810.939941,3818.199951,3744.219971,3748.570068,-0.448529,4645010000,0.811044
23829,2022-11-10,3859.889893,3958.330078,3859.889893,3956.370117,2.969661,5781260000,24.461734
23830,2022-11-11,3963.719971,4001.479980,3944.820068,3992.929932,0.185773,5593310000,-3.251021
...,...,...,...,...,...,...,...,...
23921,2023-03-27,3982.929932,4003.830078,3970.489990,3977.530029,0.300679,4233540000,-7.644684
23922,2023-03-28,3974.129883,3979.199951,3951.530029,3971.270020,-0.085484,4014600000,-5.171559
23923,2023-03-29,3999.530029,4030.590088,3999.530029,4027.810059,0.711611,4145250000,3.254372
23924,2023-03-30,4046.739990,4057.850098,4032.100098,4050.830078,0.469981,3930860000,-5.171944
23925,2023-03-31,4056.179932,4110.750000,4056.179932,4109.310059,0.132068,4525120000,15.117811

In [33]:
sp_df.to_csv(r'C:\Users\PC\Desktop\Ironhack\WR_Ironhack_Projects\Stock&Moon\sp500.csv', index = False)